# Generated by Django 3.1 on 2021-03-08 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0003_auto_20210308_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='eeg',
            fields=[
                ('eegid', models.AutoField(primary_key=True, serialize=False)),
                ('alpha', models.DecimalField(decimal_places=8, max_digits=15)),
                ('beta', models.DecimalField(decimal_places=8, max_digits=15)),
                ('theta', models.DecimalField(decimal_places=8, max_digits=15)),
                ('low_gamma', models.DecimalField(decimal_places=8, max_digits=15)),
                ('delta', models.DecimalField(decimal_places=8, max_digits=15)),
                ('interval', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
                ('sensor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
