# Generated by Django 3.1 on 2021-03-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eeg',
            name='sensor',
        ),
    ]
