# Generated by Django 3.1 on 2021-03-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr',
            fields=[
                ('hrid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('bpm', models.DecimalField(decimal_places=10, max_digits=10)),
                ('time', models.DecimalField(decimal_places=10, max_digits=10)),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
