# Generated by Django 3.1 on 2021-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20210307_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='bpm',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hr',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
