# Generated by Django 3.1 on 2021-03-08 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20210307_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='time',
        ),
        migrations.AddField(
            model_name='hr',
            name='interval',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hr',
            name='bpm',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
