# Generated by Django 3.1 on 2021-03-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20210308_1521'),
        ('hr', '0005_auto_20210308_1208'),
    ]

    operations = [
    ]
