# Generated by Django 3.1 on 2021-03-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_merge_20210308_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='time',
        ),
    ]
