# Generated by Django 3.1 on 2021-03-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spo2', '0002_auto_20210306_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spo2',
            name='time',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
