# Generated by Django 3.1 on 2021-03-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spo2', '0004_auto_20210307_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spo2',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
