# Generated by Django 3.1 on 2021-03-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalinfo',
            fields=[
                ('genid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('foodtime', models.IntegerField()),
                ('caffeine', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('healthyscale', models.IntegerField()),
                ('groups', models.IntegerField()),
                ('nicotine', models.IntegerField()),
                ('noexercise', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('msdrugs', models.IntegerField()),
                ('motionsickness', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
