# Generated by Django 3.1 on 2021-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='genid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
