# Generated by Django 3.1 on 2021-03-07 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0002_auto_20210306_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='alcohol',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='caffeine',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='foodtime',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='groups',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='healthyscale',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='motionsickness',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='msdrugs',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='nicotine',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='noexercise',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
