# Generated by Django 3.1 on 2021-03-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nausea',
            fields=[
                ('nauseaid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('trains', models.IntegerField()),
                ('airplanes', models.IntegerField()),
                ('smallboats', models.IntegerField()),
                ('ships', models.IntegerField()),
                ('swings', models.IntegerField()),
                ('roundabout', models.IntegerField()),
                ('funfair', models.IntegerField()),
                ('busses', models.IntegerField()),
                ('cars', models.IntegerField()),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
