# Generated by Django 3.1 on 2021-03-08 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0003_auto_20210308_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='emg',
            fields=[
                ('emgid', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=8, max_digits=15)),
                ('f40_132', models.DecimalField(decimal_places=8, max_digits=15)),
                ('f132_224', models.DecimalField(decimal_places=8, max_digits=15)),
                ('f224_316', models.DecimalField(decimal_places=8, max_digits=15)),
                ('f316_408', models.DecimalField(decimal_places=8, max_digits=15)),
                ('f408_500', models.DecimalField(decimal_places=8, max_digits=15)),
                ('type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('sensor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
