# Generated by Django 3.1 on 2021-03-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emg',
            old_name='type',
            new_name='interval',
        ),
    ]
