# Generated by Django 3.1 on 2021-03-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgolden',
            fields=[
                ('msgoldenid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('dizziness', models.IntegerField()),
                ('nausea', models.IntegerField()),
                ('sweat', models.IntegerField()),
                ('diffoffocus', models.IntegerField()),
                ('blurredvision', models.IntegerField()),
                ('incrsalvation', models.IntegerField()),
                ('eyestrain', models.IntegerField()),
                ('headache', models.IntegerField()),
                ('fatigue', models.IntegerField()),
                ('gendiscomfort', models.IntegerField()),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
