# Generated by Django 3.1 on 2021-03-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subjectid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('handedness', models.IntegerField()),
                ('birthyear', models.IntegerField()),
            ],
        ),
    ]
