# Generated by Django 3.1 on 2021-03-07 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='birthyear',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='handedness',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
