# Generated by Django 3.1 on 2021-03-08 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20210307_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='birthyear',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
